name: publish
on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
           username: ${{ secrets.DOCKERHUB_USER }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Get Code 
        uses: actions/checkout@v2
      -
        name: Build and push
        run: docker build . --file Dockerfile --tag leitnerfischerdhbw/es-ubuntu-x86:latest
      -
        name: Docker Push
        run: docker push leitnerfischerdhbw/es-ubuntu-x86:latest
