name: publish
on: [push]
jobs:
publish-es-ubuntu-docker-image:
runs-on: ubuntu-latest
  steps:
  - name: Checkout code
        uses: actions/checkout@v3

      # setup Docker buld action
  - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

  - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  - name: Build the Docker image # push The image to the docker hub
       run: docker build . --file Dockerfile --tag leitnerfischerdhbw/es-ubuntu-x86:latest
  - name: Docker Push
      run: docker push leitnerfischerdhbw/es-ubuntu-x86:latest